---
- name: Start local setup
  hosts: localhost
  vars:
    ansible_connection: local
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  become: true
  pre_tasks:
    - name: Pre-run | update package cache (Debian, Ubuntu)
      tags: always
      apt: update_cache=yes
      changed_when: False
      when: ansible_distribution in ["Debian", "Ubuntu"]

  roles:
    - role: base
    - role: workstation
    - role: dev

- name: Post-run | Clean-up after all
  hosts: localhost
  become: true
  tasks:
    - name: Cleanup package cache (Debian and Ubuntu)
      tags: always
      apt:
        autoclean: yes
      changed_when: false
      when: ansible_distribution in ["Debian", "Ubuntu"]

    - name: Autoremove orphan packages (Debian and Ubuntu)
      tags: always
      apt:
        autoremove: yes
        purge: yes
      when: ansible_distribution in ["Debian", "Ubuntu"]
