---
- name: swaywm | install packages
  tags: sway
  package:
    state: latest
    name:
      - alacritty
      - fonts-font-awesome
      - light
      - fuzzel
      - pavucontrol
      - pulseaudio-utils
      - sway
      - swaybg
      - swayidle
      - swayimg
      - swaylock
      - waybar

- name: sway | create sway and waybar config dirs if it does not exist
  tags: sway
  file:
    path: "/home/pascal/.config/{{ item.dir }}"
    state: directory
    mode: "0755"
  loop:
    - { dir: "sway" }
    - { dir: "sway/wp" }
    - { dir: "waybar" }

- name: Copy sway config file
  copy:
    src: "sway/{{ item.file }}"
    dest: "/home/pascal/.config/sway/{{ item.file }}"
  loop:
    - { file: "config" }
    - { file: "lock_screen.sh" }
    - { file: "mocha" }
    - { file: "status.sh" }
    - { file: "swayexit.sh" }
    - { file: "wp/taranaki2.jpeg" }

- name: Copy waybar config file
  copy:
    src: "waybar/{{ item.file }}"
    dest: "/home/pascal/.config/waybar/{{ item.file }}"
  loop:
    - { file: "config" }
    - { file: "mocha.css" }
    - { file: "style.css" }
