" general settings
set number
syntax on

" Window and splitting section
set splitbelow splitright

" Remap split navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Plugins managed by Plug plugin manager
" Install plugins by runnging the vim command :PlugInstall
call plug#begin()

Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }

" TODO requires dev role
" post install (yarn install | npm install) then load plugin only for editing supported files
Plug 'prettier/vim-prettier', { 'do': 'npm install --frozen-lockfile --production' }

call plug#end()

" plugin specific settings that may only take affect after plugin
" initialisation

" for correct catppuccin vim colours
set termguicolors
colorscheme catppuccin_mocha

map <C-o> :NERDTreeToggle<CR>

" lightline settings
let g:lightline = {'colorscheme': 'catppuccin_mocha'}
set laststatus=2

" prettier allow auto format without explicit header
let g:prettier#autoformat = 1
let g:prettier#autoformat_require_pragma = 0

" resize with Ctrl+Short 
noremap <silent> <C-S-Left> :vertical resize +1<CR>
noremap <silent> <C-S-Right> :vertical resize -1<CR>
noremap <silent> <C-S-Up> :resize +1<CR>
noremap <silent> <C-S-Down> :resize -1<CR>

" enable spell checking
set spell
set spelllang=en_gb,de_ch,de_de
