" general settings
set number
syntax on

" Window and splitting section
set splitbelow splitright

" Remap split navigation to just CTRL + hjkl
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Plugins managed by Plug plugin manager
" Install plugins by runnging the vim command :PlugInstall
call plug#begin()

Plug 'scrooloose/nerdtree'
Plug 'itchyny/lightline.vim'
Plug 'catppuccin/vim', { 'as': 'catppuccin' }

call plug#end()

" plugin specific settings that may only take affect after plugin
" initialisation

" for correct catppuccin vim colours
set termguicolors
colorscheme catppuccin_mocha

map <C-o> :NERDTreeToggle<CR>

" lightline settings
let g:lightline = {'colorscheme': 'catppuccin_mocha'}
set laststatus=2

