---

- name: add alacritty ppa repository
  apt_repository:
    repo: ppa:aslatter/ppa
      
- name: install alacritty
  package:
    state: latest
    name: alacritty

- name: copy alacritty config
  copy:
    src: "alacritty/{{ item.file }}"
    dest: "/home/pascal/.config/alacritty/{{ item.file }}"
  loop:
    - { file: "alacritty.yml" }
    - { file: "mocha.yml" }
