---

- name: Basic setup
  tags: base
  block:

  - name: Setup user pascal
    import_tasks: users/pascal.yml
    tags: user

  - name: Setup software packages
    tags: software
    block:
    
    - name: Remove unwanted software
      import_tasks: software/packages_cleanup.yml

    - name: Install install software
      import_tasks: software/packages_utilities.yml

    - name: Install and configure vim
      import_tasks: software/vim.yml
      tags: vim

    - name: Install and configure alacritty terminal
      import_tasks: software/alacritty.yml
      tags: alacritty, terminal
